## library aliases
commons-net-1.1.0.jar=commons-net:commons-net:1.1.0
dnsjava-1.6.6.jar=dnsjava:dnsjava:2.0.8
jsch-0.1.24.jar=com.jcraft:jsch:0.1.24
log4j.jar=log4j:log4j:1.2.8

# beanshell 2.0b5 is not in a maven repository
beanshell.jar=org.beanshell:bsh:2.0b4

#nanoxml-java.jar=
js.jar=rhino:js:1.6R5

# is that the right one ?
#thinlet.jar=net.sourceforge.thinlet:thinlet:2005-03-28

junit.jar=
jmock-1.0.1.jar=jmock:jmock:1.0.1
jmock-cglib-1.0.1.jar=jmock:jmock-cglib:1.0.1
asm.jar=asm:asm:1.5.3
asm-attrs.jar=asm:asm-attrs:1.5.3
asm-util.jar=asm:asm-util:1.5.3

# should we use 'cglib' instead of 'cglib-nodep' ?
cglib.jar=cglib:cglib-nodep:2.1

#mauve.jar=

ant.jar=org.apache.ant:ant:1.7.1
ant-launcher.jar=org.apache.ant:ant-launcher:1.7.1

# edtftpj 1.5.2 is not in a maven repository
edtftpj.jar=com.enterprisedt:edtFTPj:1.5.3

jcifs.jar=jcifs:jcifs:1.2.6

# ejc 3.1.1 is not in a maven repository
ejc.jar=eclipse:ejc:3.0M8

# not found in a maven repository
#oncrpc.jar=
#telnetd.jar=

# is that the right version ?
commons-logging.jar=commons-logging:commons-logging:1.1.1

# not found in a maven repository
#jawk.jar=

jetty.jar=org.mortbay.jetty:jetty:6.1.5

# jetty-util 6.1.5 is not in a maven repository
jetty-util.jar=org.eclipse.jetty:jetty-util:8.0.0.M0

# TODO
jsp.jar=
jsp-api.jar=
servlet.jar=

# is that the right version ?
derby.jar=org.apache.derby:derby:10.5.3.0_1
derbynet.jar=org.apache.derby:derbynet:10.5.3.0_1
derbytools.jar=org.apache.derby:derbytools:10.5.3.0_1

## plugins without java sources (case of external libs (see above) is handled separately)
plugins.without.java.sources=org.jnode.driver.console,org.jnode.shell.syntax

# fix some missing dependencies that are not expressed in jnode plugin descriptors
missing.dependencies.org.jnode.work=rt,org.jnode.vm.core

missing.dependencies.rt=classlib,org.jnode.vm.core
missing.dependencies.org.jnode.vm=classlib,org.jnode.vm.core

missing.dependencies.org.jnode.vm.core=classlib,org.jnode.security
missing.dependencies.org.jnode.security=org.jnode.runtime.core
missing.dependencies.org.jnode.runtime.core=classlib,nanoxml:1.4,org.jnode.util
missing.dependencies.org.jnode.util=classlib,org.apache.jakarta.log4j:1.2.8
