charva
com.jcraft.jsch
com.sun.tools.javac
com.sun.tools.jdi
derby
edtftpj
ejc
gnu.mauve
gnu.mauve.plugin
javax.ext.tools
jcifs
jetty
jnode-api
js
nanoxml
net.n3.nanoxml
net.sf.cglib
net.wimpi.telnetd
org.acplt.oncrpc
org.apache.commons.bcel
org.apache.commons.bsf
org.apache.commons.logging
org.apache.commons.net
org.apache.jakarta.log4j
org.apache.tools.ant
org.apache.tools.ant-launcher
org.apache.tools.archive
org.beanshell
org.classpath.ext
org.classpath.ext.awt
org.classpath.ext.corba
org.classpath.ext.core
org.classpath.ext.imageio
org.classpath.ext.jdwp
org.classpath.ext.management
org.classpath.ext.print
org.classpath.ext.security
org.classpath.ext.sql
org.classpath.ext.xml
org.classpath.ext.xml.ws
org.classpath.ext.xml.ws.tools
org.classpath.tools
org.jawk
org.jmock
org.jmock.cglib
org.jnode.apps.charvabsh
org.jnode.apps.commander
org.jnode.apps.console
org.jnode.apps.debug
org.jnode.apps.edit
org.jnode.apps.editor
org.jnode.apps.httpd
org.jnode.apps.jpartition
org.jnode.awt
org.jnode.awt.command
org.jnode.awt.font
org.jnode.awt.font.bdf
org.jnode.awt.font.truetype
org.jnode.awt.swingpeers
org.jnode.debug
org.jnode.debugger
org.jnode.desktop
org.jnode.driver
org.jnode.driver.block.floppy
org.jnode.driver.block.ide.disk
org.jnode.driver.block.ramdisk
org.jnode.driver.block.ramdisk.command
org.jnode.driver.block.scsi.cdrom
org.jnode.driver.block.usb.storage
org.jnode.driver.block.usb.storage.scsi
org.jnode.driver.bus.firewire
org.jnode.driver.bus.ide.atapi
org.jnode.driver.bus.pci
org.jnode.driver.bus.pcmcia
org.jnode.driver.bus.scsi
org.jnode.driver.bus.smbus
org.jnode.driver.bus.usb
org.jnode.driver.bus.usb.hub
org.jnode.driver.bus.usb.uhci
org.jnode.driver.character
org.jnode.driver.chipset
org.jnode.driver.chipset.i440BX
org.jnode.driver.chipset.via
org.jnode.driver.console
org.jnode.driver.console.swing
org.jnode.driver.finder
org.jnode.driver.input
org.jnode.driver.input.l10n
org.jnode.driver.input.usb
org.jnode.driver.net.3c90x
org.jnode.driver.net.bcm570x
org.jnode.driver.net.eepro100
org.jnode.driver.net.ethernet
org.jnode.driver.net.lance
org.jnode.driver.net.loopback
org.jnode.driver.net.ne2k-pci
org.jnode.driver.net.prism2
org.jnode.driver.net.rtl8139
org.jnode.driver.net.usb.bluetooth
org.jnode.driver.net.via_rhine
org.jnode.driver.net.wireless
org.jnode.driver.ps2
org.jnode.driver.serial
org.jnode.driver.sound.command
org.jnode.driver.sound.speaker
org.jnode.driver.sound.speaker.pc
org.jnode.driver.system.acpi
org.jnode.driver.system.cmos
org.jnode.driver.system.firmware
org.jnode.driver.system.firmware.bios
org.jnode.driver.system.pnp
org.jnode.driver.system.ram
org.jnode.driver.textscreen
org.jnode.driver.textscreen.core
org.jnode.driver.textscreen.fb
org.jnode.driver.textscreen.swing
org.jnode.driver.video
org.jnode.driver.video.ati.mach64
org.jnode.driver.video.ati.radeon
org.jnode.driver.video.cirrus
org.jnode.driver.video.cursor
org.jnode.driver.video.nvidia
org.jnode.driver.video.vesa
org.jnode.driver.video.vga
org.jnode.driver.video.vgahw
org.jnode.driver.video.vmware
org.jnode.emu
org.jnode.font.bdf
org.jnode.fs.command
org.jnode.fs.exfat
org.jnode.fs.ext2
org.jnode.fs.ext2.command
org.jnode.fs.fat
org.jnode.fs.fat.command
org.jnode.fs.ftpfs
org.jnode.fs.ftpfs.command
org.jnode.fs.hfsplus
org.jnode.fs.hfsplus.command
org.jnode.fs.hfswrapper
org.jnode.fs.initrd
org.jnode.fs.iso9660
org.jnode.fs.jfat
org.jnode.fs.jfat.command
org.jnode.fs.jifs
org.jnode.fs.jifs.command
org.jnode.fs.jifs.def
org.jnode.fs.jifs.example
org.jnode.fs.nfs
org.jnode.fs.nfs.command
org.jnode.fs.ntfs
org.jnode.fs.ramfs
org.jnode.fs.ramfs.def
org.jnode.fs.smbfs
org.jnode.fs.smbfs.command
org.jnode.games
org.jnode.install
org.jnode.log4j
org.jnode.net
org.jnode.net.arp
org.jnode.net.ipv4
org.jnode.net.ipv4.config
org.jnode.net.ipv4.core
org.jnode.net.nfs
org.jnode.partitions.apm
org.jnode.partitions.command
org.jnode.partitions.gpt
org.jnode.permission
org.jnode.protocol
org.jnode.protocol.ftp
org.jnode.protocol.nfs
org.jnode.protocol.tftp
org.jnode.runtime
org.jnode.shell
org.jnode.shell.bjorne
org.jnode.shell.command.bsh
org.jnode.shell.command.driver
org.jnode.shell.command.driver.console
org.jnode.shell.command.driver.system.acpi
org.jnode.shell.command.driver.system.bus
org.jnode.shell.command.test
org.jnode.shell.help
org.jnode.shell.syntax
org.jnode.system.repository
org.jnode.test
org.jnode.test.core
org.jnode.test.fs
org.jnode.test.fs.ext2.command
org.jnode.test.gui
org.jnode.test.net
org.jnode.test.shell
org.jnode.testrunner
org.jnode.vm.memmgr.def
org.jnode.vm.memmgr.mmtk.genrc
org.jnode.vm.memmgr.mmtk.ms
org.jnode.vm.memmgr.mmtk.nogc
org.jnode.work
org.jtestserver.server
org.junit
org.objectweb.asm
org.xbill.dns
project
project
project
project
project
project
project
project
project
project
rt
sun.tools
thinlet
fabien@pcfabien:/dev/shm/jnode_maven$ chmod +x /dev/shm/jnode_maven/scripts/find_noncyclic.py && /dev/shm/jnode_maven/scripts/find_noncyclic.py
charva
com.jcraft.jsch
com.sun.tools.javac
com.sun.tools.jdi
derby
edtftpj
ejc
gnu.mauve
gnu.mauve.plugin
javax.ext.tools
jcifs
jetty
jnode-api
js
nanoxml
net.n3.nanoxml
net.sf.cglib
net.wimpi.telnetd
org.acplt.oncrpc
org.apache.commons.bcel
org.apache.commons.bsf
org.apache.commons.logging
org.apache.commons.net
org.apache.jakarta.log4j
org.apache.tools.ant
org.apache.tools.ant-launcher
org.apache.tools.archive
org.beanshell
org.classpath.ext
org.classpath.ext.awt
org.classpath.ext.corba
org.classpath.ext.core
org.classpath.ext.imageio
org.classpath.ext.jdwp
org.classpath.ext.management
org.classpath.ext.print
org.classpath.ext.security
org.classpath.ext.sql
org.classpath.ext.xml
org.classpath.ext.xml.ws
org.classpath.ext.xml.ws.tools
org.classpath.tools
org.jawk
org.jmock
org.jmock.cglib
org.jnode.apps.charvabsh
org.jnode.apps.commander
org.jnode.apps.console
org.jnode.apps.debug
org.jnode.apps.edit
org.jnode.apps.editor
org.jnode.apps.httpd
org.jnode.apps.jpartition
org.jnode.awt
org.jnode.awt.command
org.jnode.awt.font
org.jnode.awt.font.bdf
org.jnode.awt.font.truetype
org.jnode.awt.swingpeers
org.jnode.debug
org.jnode.debugger
org.jnode.desktop
org.jnode.driver
org.jnode.driver.block.floppy
org.jnode.driver.block.ide.disk
org.jnode.driver.block.ramdisk
org.jnode.driver.block.ramdisk.command
org.jnode.driver.block.scsi.cdrom
org.jnode.driver.block.usb.storage
org.jnode.driver.block.usb.storage.scsi
org.jnode.driver.bus.firewire
org.jnode.driver.bus.ide.atapi
org.jnode.driver.bus.pci
org.jnode.driver.bus.pcmcia
org.jnode.driver.bus.scsi
org.jnode.driver.bus.smbus
org.jnode.driver.bus.usb
org.jnode.driver.bus.usb.hub
org.jnode.driver.bus.usb.uhci
org.jnode.driver.character
org.jnode.driver.chipset
org.jnode.driver.chipset.i440BX
org.jnode.driver.chipset.via
org.jnode.driver.console
org.jnode.driver.console.swing
org.jnode.driver.finder
org.jnode.driver.input
org.jnode.driver.input.l10n
org.jnode.driver.input.usb
org.jnode.driver.net.3c90x
org.jnode.driver.net.bcm570x
org.jnode.driver.net.eepro100
org.jnode.driver.net.ethernet
org.jnode.driver.net.lance
org.jnode.driver.net.loopback
org.jnode.driver.net.ne2k-pci
org.jnode.driver.net.prism2
org.jnode.driver.net.rtl8139
org.jnode.driver.net.usb.bluetooth
org.jnode.driver.net.via_rhine
org.jnode.driver.net.wireless
org.jnode.driver.ps2
org.jnode.driver.serial
org.jnode.driver.sound.command
org.jnode.driver.sound.speaker
org.jnode.driver.sound.speaker.pc
org.jnode.driver.system.acpi
org.jnode.driver.system.cmos
org.jnode.driver.system.firmware
org.jnode.driver.system.firmware.bios
org.jnode.driver.system.pnp
org.jnode.driver.system.ram
org.jnode.driver.textscreen
org.jnode.driver.textscreen.core
org.jnode.driver.textscreen.fb
org.jnode.driver.textscreen.swing
org.jnode.driver.video
org.jnode.driver.video.ati.mach64
org.jnode.driver.video.ati.radeon
org.jnode.driver.video.cirrus
org.jnode.driver.video.cursor
org.jnode.driver.video.nvidia
org.jnode.driver.video.vesa
org.jnode.driver.video.vga
org.jnode.driver.video.vgahw
org.jnode.driver.video.vmware
org.jnode.emu
org.jnode.font.bdf
org.jnode.fs.command
org.jnode.fs.exfat
org.jnode.fs.ext2
org.jnode.fs.ext2.command
org.jnode.fs.fat
org.jnode.fs.fat.command
org.jnode.fs.ftpfs
org.jnode.fs.ftpfs.command
org.jnode.fs.hfsplus
org.jnode.fs.hfsplus.command
org.jnode.fs.hfswrapper
org.jnode.fs.initrd
org.jnode.fs.iso9660
org.jnode.fs.jfat
org.jnode.fs.jfat.command
org.jnode.fs.jifs
org.jnode.fs.jifs.command
org.jnode.fs.jifs.def
org.jnode.fs.jifs.example
org.jnode.fs.nfs
org.jnode.fs.nfs.command
org.jnode.fs.ntfs
org.jnode.fs.ramfs
org.jnode.fs.ramfs.def
org.jnode.fs.smbfs
org.jnode.fs.smbfs.command
org.jnode.games
org.jnode.install
org.jnode.log4j
org.jnode.net
org.jnode.net.arp
org.jnode.net.ipv4
org.jnode.net.ipv4.config
org.jnode.net.ipv4.core
org.jnode.net.nfs
org.jnode.partitions.apm
org.jnode.partitions.command
org.jnode.partitions.gpt
org.jnode.permission
org.jnode.protocol
org.jnode.protocol.ftp
org.jnode.protocol.nfs
org.jnode.protocol.tftp
org.jnode.runtime
org.jnode.shell
org.jnode.shell.bjorne
org.jnode.shell.command.bsh
org.jnode.shell.command.driver
org.jnode.shell.command.driver.console
org.jnode.shell.command.driver.system.acpi
org.jnode.shell.command.driver.system.bus
org.jnode.shell.command.test
org.jnode.shell.help
org.jnode.shell.syntax
org.jnode.system.repository
org.jnode.test
org.jnode.test.core
org.jnode.test.fs
org.jnode.test.fs.ext2.command
org.jnode.test.gui
org.jnode.test.net
org.jnode.test.shell
org.jnode.testrunner
org.jnode.vm.memmgr.def
org.jnode.vm.memmgr.mmtk.genrc
org.jnode.vm.memmgr.mmtk.ms
org.jnode.vm.memmgr.mmtk.nogc
org.jnode.work
org.jtestserver.server
org.junit
org.objectweb.asm
org.xbill.dns
rt
sun.tools
thinlet

# small cycle
jnode.driver.console.textscreen
org.jnode.driver.console.core
# -----------